name: gitleaks
on:
  pull_request:
    branches: 
      - develop
  push:
    branches: 
      - develop
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gitleaks-action
        uses: tguff110/gitleaks-action@master
