name: gitleaks
on:
  pull_request:
    branches: 
      - develop
  push:
    branches: 
      - develop
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'  
    - name: github-actions checkout(private)
      uses: actions/checkout@v2
      with:
        repository: tguff110/github-actions
        ref: develop 
        token: ${{ secrets.GIT_ACTION_TOKEN }} # stored in GitHub secrets
        path: ./github-actions
    - name: run github-actions
      uses: ./github-actions
