name: gitleaks
on:
  pull_request:
    branches: 
      - develop
  push:
    branches: 
      - develop
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'  
    - name: gitleaks-action checkout(private)
      uses: actions/checkout@v2
      with:
        repository: <yourOrgChangeThis>/gitleaks-action
        ref: develop 
        token: ${{ secrets.GIT_ACTION_TOKEN }} # stored in GitHub secrets
        path: ./gitleaksaction
    - name: run gitleaks action
      uses: ./gitleaksaction
